name: Build

on:
  push:
    branches:
      - "main"

permissions: write-all
defaults:
  run:
    working-directory: ./plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: gradle shadowJar

      - name: Get Version
        run: |
          echo "IVY_VERSION=$(grep 'version =' build.gradle.kts | sed -E 's/.*version = "([^"]+)".*/\1/')" >> $GITHUB_ENV

      - name: Debug File System
        run: |
          tree
          find . -type f -name "Ivy.jar"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.IVY_VERSION }}
          tag_name: release-${{ github.sha }}
          make_latest: "true"
          files: |
            ./plugin/build/libs/Ivy.jar
          generate_release_notes: true